FROM node:22-alpine AS node

FROM elixir:1.17-otp-26-alpine

ENV MIX_ENV=dev \
    LANG=C.UTF-8

RUN apk add --no-cache \
  build-base \
  git \
  inotify-tools \
  postgresql-client

# Copy Node 22
COPY --from=node /usr/local/bin/node /usr/local/bin/node
COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm

WORKDIR /app

RUN mix local.hex --force && \
    mix local.rebar --force

COPY mix.exs mix.lock ./
COPY config config

RUN mix deps.get

RUN mix assets.setup

COPY . .

EXPOSE 4000
ENV PHX_SERVER=true

CMD ["mix", "phx.server"]
